// Curated landmark roster. art_key maps to the client-side silhouette registry
// (client/src/art/landmarks.ts) — keep the two in sync when adding landmarks.
// Also mirrored in client/src/data/seedPlaces.ts for the static demo build.
export type PlaceCategory = 'landmark' | 'city' | 'us-state';

export interface SeedPlace {
  name: string;
  country: string;
  description: string;
  lat: number;
  lng: number;
  artKey: string | null;
  category: PlaceCategory;
}

export const CURATED_PLACES: SeedPlace[] = [
  {
    name: 'Eiffel Tower',
    country: 'France',
    description: 'Iron lattice reaching for the Paris sky since 1889 — the city of light’s eternal exclamation mark.',
    lat: 48.8584,
    lng: 2.2945,
    artKey: 'eiffel',
    category: 'landmark',
  },
  {
    name: 'Statue of Liberty',
    country: 'United States',
    description: 'Lady Liberty lifts her torch over New York Harbor, greeting travelers as she has since 1886.',
    lat: 40.6892,
    lng: -74.0445,
    artKey: 'liberty',
    category: 'landmark',
  },
  {
    name: 'Big Ben',
    country: 'United Kingdom',
    description: 'The great bell of Westminster keeps London’s time, chiming above the Thames in Gothic splendour.',
    lat: 51.5007,
    lng: -0.1246,
    artKey: 'bigben',
    category: 'landmark',
  },
  {
    name: 'Colosseum',
    country: 'Italy',
    description: 'Rome’s mighty amphitheatre of stone arches, where fifty thousand voices once roared.',
    lat: 41.8902,
    lng: 12.4922,
    artKey: 'colosseum',
    category: 'landmark',
  },
  {
    name: 'Taj Mahal',
    country: 'India',
    description: 'A marble love letter on the Yamuna’s banks, glowing rose and ivory at dawn.',
    lat: 27.1751,
    lng: 78.0421,
    artKey: 'tajmahal',
    category: 'landmark',
  },
  {
    name: 'Great Pyramid of Giza',
    country: 'Egypt',
    description: 'Four and a half millennia of desert sun on the last standing wonder of the ancient world.',
    lat: 29.9792,
    lng: 31.1342,
    artKey: 'pyramids',
    category: 'landmark',
  },
  {
    name: 'Sydney Opera House',
    country: 'Australia',
    description: 'White sails billowing on Bennelong Point — the harbour’s grandest performance.',
    lat: -33.8568,
    lng: 151.2153,
    artKey: 'operahouse',
    category: 'landmark',
  },
  {
    name: 'Golden Gate Bridge',
    country: 'United States',
    description: 'International-orange towers striding through the fog at the gate of the Pacific.',
    lat: 37.8199,
    lng: -122.4783,
    artKey: 'goldengate',
    category: 'landmark',
  },
  {
    name: 'Christ the Redeemer',
    country: 'Brazil',
    description: 'Arms open wide above Rio, embracing beaches, samba, and the Sugarloaf below.',
    lat: -22.9519,
    lng: -43.2105,
    artKey: 'redeemer',
    category: 'landmark',
  },
  {
    name: 'Machu Picchu',
    country: 'Peru',
    description: 'The lost citadel of the Incas, terraced into cloud forest high above the Urubamba.',
    lat: -13.1631,
    lng: -72.545,
    artKey: 'machu',
    category: 'landmark',
  },
  {
    name: 'Mount Fuji',
    country: 'Japan',
    description: 'The sacred snow-capped cone rising in perfect symmetry over lakes and pine.',
    lat: 35.3606,
    lng: 138.7274,
    artKey: 'fuji',
    category: 'landmark',
  },
  {
    name: 'Fushimi Inari Shrine',
    country: 'Japan',
    description: 'Ten thousand vermilion torii gates winding up the wooded slopes of Kyoto.',
    lat: 34.9671,
    lng: 135.7727,
    artKey: 'torii',
    category: 'landmark',
  },
  {
    name: 'Sagrada Família',
    country: 'Spain',
    description: 'Gaudí’s unfinished symphony in stone, its spires still climbing over Barcelona.',
    lat: 41.4036,
    lng: 2.1744,
    artKey: 'sagrada',
    category: 'landmark',
  },
  {
    name: 'Brandenburg Gate',
    country: 'Germany',
    description: 'Berlin’s neoclassical triumph, where the Quadriga rides toward a reunited city.',
    lat: 52.5163,
    lng: 13.3777,
    artKey: 'brandenburg',
    category: 'landmark',
  },
  {
    name: 'Burj Khalifa',
    country: 'United Arab Emirates',
    description: 'A silver needle stitching the Dubai desert to the clouds — the world’s tallest view.',
    lat: 25.1972,
    lng: 55.2744,
    artKey: 'burj',
    category: 'landmark',
  },
  {
    name: 'Petra',
    country: 'Jordan',
    description: 'The rose-red Treasury carved into a desert canyon, revealed by a crack in the rock.',
    lat: 30.3285,
    lng: 35.4444,
    artKey: 'petra',
    category: 'landmark',
  },
  {
    name: 'Angkor Wat',
    country: 'Cambodia',
    description: 'Lotus-bud towers mirrored in still water — the largest temple the world has known.',
    lat: 13.4125,
    lng: 103.867,
    artKey: 'angkor',
    category: 'landmark',
  },
  {
    name: 'Great Wall at Mutianyu',
    country: 'China',
    description: 'Watchtowers riding the ridgelines, a stone dragon asleep across the mountains.',
    lat: 40.4319,
    lng: 116.5704,
    artKey: 'greatwall',
    category: 'landmark',
  },
  {
    name: 'Moai of Rapa Nui',
    country: 'Chile',
    description: 'Silent stone ancestors gazing inland over the loneliest island in the sea.',
    lat: -27.1258,
    lng: -109.2769,
    artKey: 'moai',
    category: 'landmark',
  },
  {
    name: 'Table Mountain',
    country: 'South Africa',
    description: 'A flat-topped sentinel draped in its tablecloth of cloud above Cape Town.',
    lat: -33.9628,
    lng: 18.4098,
    artKey: 'tablemountain',
    category: 'landmark',
  },
  {
    name: 'Niagara Falls',
    country: 'Canada',
    description: 'A thundering horseshoe of white water on the border of two nations.',
    lat: 43.0962,
    lng: -79.0377,
    artKey: 'niagara',
    category: 'landmark',
  },
  {
    name: 'Oia, Santorini',
    country: 'Greece',
    description: 'Whitewashed houses and blue domes tumbling down the caldera into the Aegean.',
    lat: 36.4618,
    lng: 25.3753,
    artKey: 'santorini',
    category: 'landmark',
  },
  {
    name: 'Neuschwanstein Castle',
    country: 'Germany',
    description: 'The fairy-tale king’s castle of turrets and towers, adrift in Alpine mist.',
    lat: 47.5576,
    lng: 10.7498,
    artKey: 'neuschwanstein',
    category: 'landmark',
  },
  {
    name: 'Acropolis of Athens',
    country: 'Greece',
    description: 'The Parthenon’s marble columns catching golden light above the ancient city.',
    lat: 37.9715,
    lng: 23.7267,
    artKey: 'acropolis',
    category: 'landmark',
  },
  {
    name: 'Gyeongbokgung Palace',
    country: 'South Korea',
    description: 'Joseon-dynasty pavilions and guard changes beneath Seoul’s mountain skyline.',
    lat: 37.5796,
    lng: 126.977,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Wat Arun',
    country: 'Thailand',
    description: 'The Temple of Dawn glitters with porcelain mosaics on the banks of the Chao Phraya.',
    lat: 13.7437,
    lng: 100.4888,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Ha Long Bay',
    country: 'Vietnam',
    description: 'Thousands of limestone karsts rising from emerald water, wrapped in legend.',
    lat: 20.9101,
    lng: 107.1839,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Borobudur',
    country: 'Indonesia',
    description: 'The world’s largest Buddhist temple, its stupas watching the Java mist lift at dawn.',
    lat: -7.6079,
    lng: 110.2038,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Chocolate Hills',
    country: 'Philippines',
    description: 'Over a thousand cone-shaped hills turning cocoa-brown across Bohol in the dry season.',
    lat: 9.8167,
    lng: 124.1667,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Petronas Towers',
    country: 'Malaysia',
    description: 'Twin steel spires linked by a skybridge, once the tallest buildings on Earth.',
    lat: 3.1579,
    lng: 101.7116,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Marina Bay Sands',
    country: 'Singapore',
    description: 'A rooftop infinity pool crowning three towers above the Lion City’s skyline.',
    lat: 1.2834,
    lng: 103.8607,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Boudhanath Stupa',
    country: 'Nepal',
    description: 'Painted eyes gaze from every direction over Kathmandu’s largest Buddhist stupa.',
    lat: 27.7215,
    lng: 85.362,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Sigiriya',
    country: 'Sri Lanka',
    description: 'An ancient rock fortress rising sheer from the jungle, frescoes still bright on its flank.',
    lat: 7.957,
    lng: 80.7603,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Shwedagon Pagoda',
    country: 'Myanmar',
    description: 'A gilded stupa said to enshrine relics of four Buddhas, glowing over Yangon at dusk.',
    lat: 16.7983,
    lng: 96.1495,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Genghis Khan Equestrian Statue',
    country: 'Mongolia',
    description: 'The largest equestrian statue in the world, steel and steppe wind on the Mongolian plain.',
    lat: 47.8467,
    lng: 106.9633,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Hagia Sophia',
    country: 'Turkey',
    description: 'Byzantine dome and Ottoman minarets layered into one building across fifteen centuries.',
    lat: 41.0086,
    lng: 28.9802,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Western Wall',
    country: 'Israel',
    description: 'The last remnant of the Second Temple, notes tucked into every reachable crevice.',
    lat: 31.7767,
    lng: 35.2345,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Masjid al-Haram',
    country: 'Saudi Arabia',
    description: 'Islam’s holiest site, encircling the Kaaba at the heart of Mecca.',
    lat: 21.4225,
    lng: 39.8262,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Museum of Islamic Art',
    country: 'Qatar',
    description: 'I.M. Pei’s limestone geometry standing on its own island in Doha Bay.',
    lat: 25.2949,
    lng: 51.539,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Saint Basil’s Cathedral',
    country: 'Russia',
    description: 'Swirling onion domes in candy colors anchoring the south end of Red Square.',
    lat: 55.7525,
    lng: 37.6231,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Bayterek Tower',
    country: 'Kazakhstan',
    description: 'A golden orb atop a white lattice tower, the mythic tree of life reimagined in steel.',
    lat: 51.1284,
    lng: 71.4306,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Zaanse Schans Windmills',
    country: 'Netherlands',
    description: 'Working windmills line the Zaan, sails turning as they have for three centuries.',
    lat: 52.4747,
    lng: 4.8172,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Belém Tower',
    country: 'Portugal',
    description: 'A Manueline fortress that watched Portugal’s caravels sail for the New World.',
    lat: 38.6916,
    lng: -9.216,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Cliffs of Moher',
    country: 'Ireland',
    description: 'Sheer Atlantic cliffs climbing 700 feet above the crashing County Clare surf.',
    lat: 52.9715,
    lng: -9.4309,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Gullfoss',
    country: 'Iceland',
    description: 'The Golden Falls thunder into a jagged canyon on Iceland’s Golden Circle.',
    lat: 64.3271,
    lng: -20.1199,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Preikestolen',
    country: 'Norway',
    description: 'Pulpit Rock juts 600 meters above Lysefjord, a flat stone stage over the water.',
    lat: 58.9866,
    lng: 6.1902,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Gamla Stan',
    country: 'Sweden',
    description: 'Cobbled medieval lanes and ochre façades on Stockholm’s old-town island.',
    lat: 59.3251,
    lng: 18.0711,
    artKey: null,
    category: 'city',
  },
  {
    name: 'The Little Mermaid',
    country: 'Denmark',
    description: 'A small bronze statue on a harbor rock, watching ferries leave Copenhagen.',
    lat: 55.6929,
    lng: 12.5993,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Helsinki Cathedral',
    country: 'Finland',
    description: 'Neoclassical white and green domes crowning Senate Square in the midnight sun.',
    lat: 60.1699,
    lng: 24.9525,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Matterhorn',
    country: 'Switzerland',
    description: 'A near-perfect pyramid of rock and ice, the most photographed peak in the Alps.',
    lat: 45.9763,
    lng: 7.6586,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Hallstatt',
    country: 'Austria',
    description: 'A lakeside village of pastel houses stacked beneath alpine cliffs.',
    lat: 47.5622,
    lng: 13.6493,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Charles Bridge',
    country: 'Czech Republic',
    description: 'Gothic statues line a stone bridge over the Vltava, Prague Castle floating above.',
    lat: 50.0865,
    lng: 14.4114,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Hungarian Parliament Building',
    country: 'Hungary',
    description: 'Neo-Gothic spires and a river-facing façade lit gold along the Danube.',
    lat: 47.507,
    lng: 19.0458,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Wawel Castle',
    country: 'Poland',
    description: 'A royal fortress of brick towers overlooking the Vistula in Kraków.',
    lat: 50.0544,
    lng: 19.9356,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Dubrovnik Old Town',
    country: 'Croatia',
    description: 'Limestone walls encircle terracotta rooftops tumbling to the Adriatic.',
    lat: 42.6407,
    lng: 18.1077,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Grand Place',
    country: 'Belgium',
    description: 'Gilded guild halls ring Brussels’ medieval market square.',
    lat: 50.8467,
    lng: 4.3525,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Edinburgh Castle',
    country: 'United Kingdom',
    description: 'A fortress on an extinct volcano, guarding Scotland’s capital for nine centuries.',
    lat: 55.9486,
    lng: -3.1999,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'St. Peter’s Basilica',
    country: 'Vatican City',
    description: 'Michelangelo’s dome rises over the piazza at the heart of the Catholic world.',
    lat: 41.9022,
    lng: 12.4539,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Monte Carlo Casino',
    country: 'Monaco',
    description: 'Belle Époque grandeur on the Riviera, roulette wheels spinning since 1863.',
    lat: 43.7396,
    lng: 7.4308,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'CN Tower',
    country: 'Canada',
    description: 'A concrete needle over Toronto with a glass floor not for the faint of heart.',
    lat: 43.6426,
    lng: -79.3871,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Banff National Park',
    country: 'Canada',
    description: 'Turquoise glacial lakes ringed by the jagged peaks of the Canadian Rockies.',
    lat: 51.4968,
    lng: -115.9281,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Chichén Itzá',
    country: 'Mexico',
    description: 'El Castillo’s stepped pyramid marks the equinox with a shadow-serpent on its stairs.',
    lat: 20.6843,
    lng: -88.5678,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Tikal',
    country: 'Guatemala',
    description: 'Maya temple-pyramids break through the jungle canopy of the Petén rainforest.',
    lat: 17.222,
    lng: -89.6237,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Old Havana',
    country: 'Cuba',
    description: 'Pastel colonial façades and vintage cars line streets facing the Malecón.',
    lat: 23.1367,
    lng: -82.3589,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Dunn’s River Falls',
    country: 'Jamaica',
    description: 'Terraced limestone cascades tumble straight into the Caribbean Sea.',
    lat: 18.4139,
    lng: -77.1319,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Iguazu Falls',
    country: 'Argentina',
    description: 'Hundreds of cataracts roar across the Argentina–Brazil border in a cloud of mist.',
    lat: -25.6953,
    lng: -54.4367,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Torres del Paine',
    country: 'Chile',
    description: 'Granite towers pierce Patagonian sky above turquoise lakes and wind-bent trees.',
    lat: -50.9423,
    lng: -73.4068,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Salar de Uyuni',
    country: 'Bolivia',
    description: 'The world’s largest salt flat turns into a mirror of the sky after rain.',
    lat: -20.1338,
    lng: -67.4891,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Cartagena Old Town',
    country: 'Colombia',
    description: 'Walled colonial streets in every color, facing the Caribbean behind centuries-old ramparts.',
    lat: 10.4236,
    lng: -75.5482,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Galápagos Islands',
    country: 'Ecuador',
    description: 'Volcanic islands where giant tortoises and finches inspired a theory of evolution.',
    lat: -0.9538,
    lng: -90.9656,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Angel Falls',
    country: 'Venezuela',
    description: 'Water plunges nearly a kilometer off a tepui into the Venezuelan jungle below.',
    lat: 5.9701,
    lng: -62.5362,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Jemaa el-Fnaa',
    country: 'Morocco',
    description: 'Snake charmers, spice stalls, and storytellers fill Marrakesh’s ancient main square at dusk.',
    lat: 31.6258,
    lng: -7.9891,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Maasai Mara',
    country: 'Kenya',
    description: 'Endless savanna where wildebeest herds thunder across the Mara River each year.',
    lat: -1.5,
    lng: 35.1,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Mount Kilimanjaro',
    country: 'Tanzania',
    description: 'Africa’s highest peak, snow-capped at the equator above the Tanzanian plains.',
    lat: -3.0674,
    lng: 37.3556,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Victoria Falls',
    country: 'Zambia',
    description: 'The Zambezi plunges into a churning gorge in a curtain of spray visible for miles.',
    lat: -17.9243,
    lng: 25.8572,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Sossusvlei',
    country: 'Namibia',
    description: 'Towering red dunes cradle a bone-white salt pan deep in the Namib Desert.',
    lat: -24.7333,
    lng: 15.3,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Zuma Rock',
    country: 'Nigeria',
    description: 'A sheer 725-meter monolith standing sentinel over the road to Abuja.',
    lat: 9.1211,
    lng: 7.2062,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Lalibela Rock Churches',
    country: 'Ethiopia',
    description: 'Eleven medieval churches carved downward into solid volcanic rock.',
    lat: 12.0316,
    lng: 39.0473,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Amphitheatre of El Jem',
    country: 'Tunisia',
    description: 'A Roman colosseum rising improbably from the Tunisian plain, still nearly whole.',
    lat: 35.2967,
    lng: 10.705,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Okavango Delta',
    country: 'Botswana',
    description: 'A river that never reaches the sea, fanning into a lush inland delta instead.',
    lat: -19.2833,
    lng: 22.9833,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Cape Coast Castle',
    country: 'Ghana',
    description: 'Whitewashed ramparts on the Gulf of Guinea, holding centuries of hard history.',
    lat: 5.1053,
    lng: -1.2466,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Milford Sound',
    country: 'New Zealand',
    description: 'Sheer fjord walls and waterfalls drop straight into still, dark water.',
    lat: -44.671,
    lng: 167.925,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Bora Bora',
    country: 'French Polynesia',
    description: 'An extinct volcano ringed by a lagoon of impossible turquoise.',
    lat: -16.5004,
    lng: -151.7415,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'U.S. Space & Rocket Center',
    country: 'United States',
    description: 'Saturn V rockets stand on end where Huntsville helped put astronauts on the Moon.',
    lat: 34.7196,
    lng: -86.6503,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Denali',
    country: 'United States',
    description: 'North America’s tallest peak, its own weather system wreathing the summit in cloud.',
    lat: 63.0692,
    lng: -151.007,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Grand Canyon',
    country: 'United States',
    description: 'A mile-deep gash of banded red rock carved by the Colorado River over eons.',
    lat: 36.1069,
    lng: -112.1129,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Hot Springs National Park',
    country: 'United States',
    description: 'Steaming thermal water still flows through this bathhouse row in the Ouachitas.',
    lat: 34.5037,
    lng: -93.0552,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Yosemite Valley',
    country: 'United States',
    description: 'Granite cliffs and waterfalls tower over a valley carved by ancient glaciers.',
    lat: 37.7459,
    lng: -119.5936,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Rocky Mountain National Park',
    country: 'United States',
    description: 'A road climbs above the treeline into tundra ringed by fourteen-thousand-foot peaks.',
    lat: 40.3428,
    lng: -105.6836,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Mystic Seaport',
    country: 'United States',
    description: 'Tall ships and a recreated whaling village line the banks of the Mystic River.',
    lat: 41.3712,
    lng: -71.9662,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Rehoboth Beach Boardwalk',
    country: 'United States',
    description: 'Saltwater taffy and Atlantic breeze along Delaware’s classic seaside boardwalk.',
    lat: 38.7209,
    lng: -75.076,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Cinderella Castle',
    country: 'United States',
    description: 'A fairy-tale spire at the heart of the Magic Kingdom in Orlando.',
    lat: 28.4177,
    lng: -81.5812,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Stone Mountain',
    country: 'United States',
    description: 'The largest exposed granite monolith on Earth, carved with a Confederate memorial relief.',
    lat: 33.8055,
    lng: -84.1455,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Diamond Head',
    country: 'United States',
    description: 'A volcanic tuff cone crater standing guard over Waikiki Beach.',
    lat: 21.262,
    lng: -157.8058,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Shoshone Falls',
    country: 'United States',
    description: 'The “Niagara of the West” drops over a horseshoe rim on the Snake River.',
    lat: 42.5946,
    lng: -114.4001,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Cloud Gate',
    country: 'United States',
    description: 'A liquid-mercury sculpture — “The Bean” — mirrors Chicago’s skyline in Millennium Park.',
    lat: 41.8827,
    lng: -87.6233,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Indianapolis Motor Speedway',
    country: 'United States',
    description: 'The “Brickyard” has hosted the Indy 500 on its oval since 1911.',
    lat: 39.795,
    lng: -86.2347,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Field of Dreams',
    country: 'United States',
    description: 'A baseball diamond cut into an Iowa cornfield, straight out of the movie.',
    lat: 42.493,
    lng: -91.0182,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Monument Rocks',
    country: 'United States',
    description: 'Chalk badland spires rise from the Kansas prairie, remnants of an ancient seabed.',
    lat: 38.7909,
    lng: -100.748,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Mammoth Cave',
    country: 'United States',
    description: 'The longest known cave system on Earth, still being mapped beneath the Kentucky hills.',
    lat: 37.1862,
    lng: -86.1,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'French Quarter',
    country: 'United States',
    description: 'Wrought-iron balconies and jazz spill onto the streets of old New Orleans.',
    lat: 29.9584,
    lng: -90.0644,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Acadia National Park',
    country: 'United States',
    description: 'Pink granite headlands meet the Atlantic where the sunrise hits the U.S. first.',
    lat: 44.3386,
    lng: -68.2733,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Fort McHenry',
    country: 'United States',
    description: 'The star-shaped fort whose overnight bombardment inspired the national anthem.',
    lat: 39.2627,
    lng: -76.5797,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Bunker Hill Monument',
    country: 'United States',
    description: 'A granite obelisk on Boston’s Freedom Trail marks the Revolution’s bloodiest battle.',
    lat: 42.3763,
    lng: -71.0611,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Mackinac Bridge',
    country: 'United States',
    description: 'A five-mile suspension bridge links Michigan’s two peninsulas over the Straits.',
    lat: 45.818,
    lng: -84.7278,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Split Rock Lighthouse',
    country: 'United States',
    description: 'A century-old beacon on a sheer cliff above the vast, cold expanse of Lake Superior.',
    lat: 47.2,
    lng: -91.3675,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Vicksburg National Military Park',
    country: 'United States',
    description: 'Monuments and earthworks mark the Civil War siege that split the Confederacy.',
    lat: 32.3466,
    lng: -90.857,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Gateway Arch',
    country: 'United States',
    description: 'A gleaming stainless-steel catenary curve framing the St. Louis riverfront.',
    lat: 38.6247,
    lng: -90.1848,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Glacier National Park',
    country: 'United States',
    description: 'The Going-to-the-Sun Road climbs through jagged peaks and ancient ice fields.',
    lat: 48.696,
    lng: -113.718,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Chimney Rock',
    country: 'United States',
    description: 'A slender spire that guided a century of wagon trains along the Oregon Trail.',
    lat: 41.7027,
    lng: -103.348,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Hoover Dam',
    country: 'United States',
    description: 'An Art Deco curve of concrete holding back the Colorado River in Black Canyon.',
    lat: 36.0161,
    lng: -114.7377,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Mount Washington',
    country: 'United States',
    description: 'The Northeast’s highest peak, once clocked with the fastest surface wind on Earth.',
    lat: 44.2706,
    lng: -71.3033,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Atlantic City Boardwalk',
    country: 'United States',
    description: 'The original boardwalk, saltwater taffy, casinos, and the Atlantic all in a row.',
    lat: 39.3643,
    lng: -74.4229,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'White Sands',
    country: 'United States',
    description: 'Gypsum dunes ripple white to the horizon in the Tularosa Basin.',
    lat: 32.7871,
    lng: -106.3255,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Empire State Building',
    country: 'United States',
    description: 'An Art Deco spire that ruled the Manhattan skyline for four decades.',
    lat: 40.7484,
    lng: -73.9857,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Wright Brothers National Memorial',
    country: 'United States',
    description: 'The dunes of Kitty Hawk where twelve seconds of flight changed the world.',
    lat: 36.0128,
    lng: -75.6707,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Theodore Roosevelt National Park',
    country: 'United States',
    description: 'Painted badlands and bison roam the park named for its conservationist president.',
    lat: 46.9789,
    lng: -103.5382,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Rock & Roll Hall of Fame',
    country: 'United States',
    description: 'A glass pyramid on Lake Erie’s shore honoring music’s loudest rebels.',
    lat: 41.5087,
    lng: -81.695,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Oklahoma City National Memorial',
    country: 'United States',
    description: 'A field of empty chairs and a reflecting pool mark a moment of resilience.',
    lat: 35.473,
    lng: -97.5171,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Crater Lake',
    country: 'United States',
    description: 'The deepest lake in the U.S. fills a collapsed volcano with impossibly blue water.',
    lat: 42.9446,
    lng: -122.109,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Liberty Bell',
    country: 'United States',
    description: 'A cracked bronze bell in Philadelphia, rung to proclaim American independence.',
    lat: 39.9496,
    lng: -75.1503,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'The Breakers',
    country: 'United States',
    description: 'A Gilded Age Vanderbilt mansion overlooking the cliffs of Newport.',
    lat: 41.4694,
    lng: -71.2999,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Fort Sumter',
    country: 'United States',
    description: 'The harbor fort where the first shots of the Civil War were fired.',
    lat: 32.7523,
    lng: -79.8748,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Mount Rushmore',
    country: 'United States',
    description: 'Four presidents’ faces carved sixty feet tall into the Black Hills granite.',
    lat: 43.8791,
    lng: -103.4591,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Great Smoky Mountains',
    country: 'United States',
    description: 'Blue-hazed ridgelines roll to the horizon in America’s most-visited national park.',
    lat: 35.6118,
    lng: -83.4895,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'The Alamo',
    country: 'United States',
    description: 'A former mission in San Antonio, remembered for a thirteen-day siege in 1836.',
    lat: 29.426,
    lng: -98.4861,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Arches National Park',
    country: 'United States',
    description: 'Over two thousand natural sandstone arches rise from Utah’s red desert.',
    lat: 38.7331,
    lng: -109.5925,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Vermont State House',
    country: 'United States',
    description: 'A gold-domed capitol standing against Vermont’s forested Green Mountains.',
    lat: 44.2601,
    lng: -72.5754,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Monticello',
    country: 'United States',
    description: 'Thomas Jefferson’s neoclassical hilltop home, designed down to the last detail.',
    lat: 38.0084,
    lng: -78.4529,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Space Needle',
    country: 'United States',
    description: 'A flying-saucer-topped tower built for the 1962 World’s Fair, still Seattle’s icon.',
    lat: 47.6205,
    lng: -122.3493,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'New River Gorge Bridge',
    country: 'United States',
    description: 'One of the world’s highest steel arch bridges, spanning an ancient river gorge.',
    lat: 38.0676,
    lng: -81.0778,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Wisconsin Dells',
    country: 'United States',
    description: 'Sandstone canyons carved by glacial floodwaters along the Wisconsin River.',
    lat: 43.6274,
    lng: -89.771,
    artKey: null,
    category: 'us-state',
  },
  {
    name: 'Old Faithful',
    country: 'United States',
    description: 'Yellowstone’s most punctual geyser, erupting on a clockwork schedule since 1870.',
    lat: 44.4605,
    lng: -110.8281,
    artKey: null,
    category: 'us-state',
  },

  // Additional world landmarks (Europe, Asia, Africa, the Americas, Oceania).
  {
    name: 'Mont Saint-Michel',
    country: 'France',
    description: 'A tidal island abbey rising from Norman sandflats, ramparts ringed by the sea twice a day.',
    lat: 48.6361,
    lng: -1.5115,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Palace of Versailles',
    country: 'France',
    description: 'The Sun King’s hall of mirrors and manicured gardens, built to outshine every court in Europe.',
    lat: 48.8049,
    lng: 2.1204,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Louvre Museum',
    country: 'France',
    description: 'A glass pyramid marks the entrance to the world’s largest art museum, once a royal palace.',
    lat: 48.8606,
    lng: 2.3376,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Leaning Tower of Pisa',
    country: 'Italy',
    description: 'An eight-century construction blunder tilts photogenically over the Field of Miracles.',
    lat: 43.723,
    lng: 10.3966,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Piazza San Marco',
    country: 'Italy',
    description: 'Gondolas glide past Byzantine domes on the square Napoleon called Europe’s finest drawing room.',
    lat: 45.4341,
    lng: 12.3388,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Positano',
    country: 'Italy',
    description: 'Pastel houses cascade down cliffs to the sea along Italy’s most vertiginous coastline.',
    lat: 40.628,
    lng: 14.4849,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Alhambra',
    country: 'Spain',
    description: 'Moorish palaces of carved stucco and reflecting pools crown a red hill above Granada.',
    lat: 37.176,
    lng: -3.5883,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Park Güell',
    country: 'Spain',
    description: 'Gaudí’s mosaic-tiled terraces and gingerbread pavilions overlook Barcelona in broken color.',
    lat: 41.4145,
    lng: 2.1527,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Stonehenge',
    country: 'United Kingdom',
    description: 'A ring of five-thousand-year-old standing stones aligned to the solstice sun on Salisbury Plain.',
    lat: 51.1789,
    lng: -1.8262,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Tower Bridge',
    country: 'United Kingdom',
    description: 'Twin Victorian towers raise a bascule deck to let tall ships pass beneath the Thames.',
    lat: 51.5055,
    lng: -0.0754,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Cologne Cathedral',
    country: 'Germany',
    description: 'Twin Gothic spires took six centuries to finish, surviving as the city’s wartime landmark.',
    lat: 50.9413,
    lng: 6.9583,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Meteora',
    country: 'Greece',
    description: 'Byzantine monasteries perch atop sheer sandstone pillars rising from the Thessalian plain.',
    lat: 39.7217,
    lng: 21.6306,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Cappadocia',
    country: 'Turkey',
    description: 'Hot-air balloons drift at dawn over fairy chimneys carved by wind and ancient cave dwellers.',
    lat: 38.6431,
    lng: 34.8289,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Pamukkale',
    country: 'Turkey',
    description: 'Terraces of blinding-white travertine cascade with mineral pools above the Anatolian plateau.',
    lat: 37.9203,
    lng: 29.1211,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Hermitage Museum',
    country: 'Russia',
    description: 'The Winter Palace’s emerald façade holds one of the world’s great art collections on the Neva.',
    lat: 59.9398,
    lng: 30.3146,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Kyiv Pechersk Lavra',
    country: 'Ukraine',
    description: 'Golden domes crown a cave monastery overlooking the Dnipro, founded nearly a thousand years ago.',
    lat: 50.4344,
    lng: 30.557,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Bran Castle',
    country: 'Romania',
    description: 'Turreted battlements on a Transylvanian crag lend themselves to a certain vampire legend.',
    lat: 45.5149,
    lng: 25.3672,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Rila Monastery',
    country: 'Bulgaria',
    description: 'Striped arches and frescoed courtyards hide deep in the Rila mountains south of Sofia.',
    lat: 42.1333,
    lng: 23.34,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Lake Bled',
    country: 'Slovenia',
    description: 'A church-topped islet floats on turquoise water beneath an Alpine cliffside castle.',
    lat: 46.3683,
    lng: 14.1146,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Kotor Old Town',
    country: 'Montenegro',
    description: 'Venetian walls climb the mountainside above a fjord-like bay on the Adriatic.',
    lat: 42.4247,
    lng: 18.7712,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Belgrade Fortress',
    country: 'Serbia',
    description: 'Ramparts built by Celts, Romans, and Ottomans in turn overlook the Sava and Danube confluence.',
    lat: 44.8225,
    lng: 20.4487,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Stari Most',
    country: 'Bosnia and Herzegovina',
    description: 'A single stone arch bridges the Neretva at Mostar, rebuilt stone by stone after the war.',
    lat: 43.3373,
    lng: 17.8151,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Lake Ohrid',
    country: 'North Macedonia',
    description: 'One of Europe’s oldest and deepest lakes, ringed by Byzantine churches and orchards.',
    lat: 41.1231,
    lng: 20.7969,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Vilnius Old Town',
    country: 'Lithuania',
    description: 'Baroque spires and cobbled lanes fill one of Europe’s largest surviving medieval old towns.',
    lat: 54.6872,
    lng: 25.2797,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Riga Old Town',
    country: 'Latvia',
    description: 'Art Nouveau façades and a Hanseatic skyline rise where the Daugava meets the Baltic.',
    lat: 56.9496,
    lng: 24.1052,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Tallinn Old Town',
    country: 'Estonia',
    description: 'Turreted walls and spires make one of Europe’s best-preserved medieval capitals.',
    lat: 59.437,
    lng: 24.7454,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Luxembourg Old City',
    country: 'Luxembourg',
    description: 'Fortress casemates riddle the cliffs beneath a capital perched over the Alzette gorge.',
    lat: 49.6116,
    lng: 6.1319,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Valletta',
    country: 'Malta',
    description: 'Baroque limestone bastions built by the Knights of St. John ring a harbor of golden stone.',
    lat: 35.8989,
    lng: 14.5146,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Kourion',
    country: 'Cyprus',
    description: 'A clifftop Greco-Roman theatre still stages shows above the Mediterranean surf.',
    lat: 34.6636,
    lng: 32.8869,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Berat',
    country: 'Albania',
    description: 'The City of a Thousand Windows stacks Ottoman houses in tiers above the Osum River.',
    lat: 40.7058,
    lng: 19.9522,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Forbidden City',
    country: 'China',
    description: 'Nine hundred imperial rooms behind vermilion walls, off-limits to commoners for five centuries.',
    lat: 39.9163,
    lng: 116.3972,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Zhangjiajie',
    country: 'China',
    description: 'Thousands of quartzite pillars rise from mist-wrapped forest, said to have inspired Avatar.',
    lat: 29.3167,
    lng: 110.4792,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Terracotta Army',
    country: 'China',
    description: 'Eight thousand life-sized clay soldiers stand guard over a buried emperor near Xi’an.',
    lat: 34.3853,
    lng: 109.2734,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Kinkaku-ji',
    country: 'Japan',
    description: 'A gold-leafed pavilion mirrors itself in a still pond among Kyoto’s pines.',
    lat: 35.0394,
    lng: 135.7292,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Shibuya Crossing',
    country: 'Japan',
    description: 'Up to three thousand pedestrians surge across Tokyo’s busiest intersection with every light change.',
    lat: 35.6595,
    lng: 139.7005,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Osaka Castle',
    country: 'Japan',
    description: 'Green-tiled turrets rise from stone ramparts once central to unifying feudal Japan.',
    lat: 34.6873,
    lng: 135.5262,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Amber Fort',
    country: 'India',
    description: 'Mirrored halls and ramparts of pale sandstone overlook a lake near Jaipur.',
    lat: 26.9855,
    lng: 75.8513,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Varanasi Ghats',
    country: 'India',
    description: 'Stone steps line the Ganges where pilgrims bathe at dawn in one of the world’s oldest cities.',
    lat: 25.3109,
    lng: 83.0107,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Hawa Mahal',
    country: 'India',
    description: 'A honeycomb façade of 953 pink sandstone windows once let royal women watch the street unseen.',
    lat: 26.9239,
    lng: 75.8267,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Seongsan Ilchulbong',
    country: 'South Korea',
    description: 'A volcanic tuff cone rises from the sea off Jeju Island, its crater rim a sunrise pilgrimage.',
    lat: 33.4587,
    lng: 126.9425,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Bukchon Hanok Village',
    country: 'South Korea',
    description: 'Traditional wood-and-tile hanok houses climb a hillside between two of Seoul’s royal palaces.',
    lat: 37.5826,
    lng: 126.9831,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Uluwatu Temple',
    country: 'Indonesia',
    description: 'A Balinese sea temple balances on a limestone cliff two hundred feet above crashing surf.',
    lat: -8.8291,
    lng: 115.0849,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Komodo National Park',
    country: 'Indonesia',
    description: 'Pink-sand beaches and ancient monitor lizards share a volcanic archipelago in the Flores Sea.',
    lat: -8.5455,
    lng: 119.4894,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Grand Palace',
    country: 'Thailand',
    description: 'Glittering spires and the Emerald Buddha fill the former royal compound on the Chao Phraya.',
    lat: 13.75,
    lng: 100.4913,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Phi Phi Islands',
    country: 'Thailand',
    description: 'Limestone karsts ring a turquoise lagoon made famous long before it was famous.',
    lat: 7.7407,
    lng: 98.7784,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Hoi An Ancient Town',
    country: 'Vietnam',
    description: 'Lantern-lit streets and a Japanese covered bridge preserve a five-century trading port.',
    lat: 15.8801,
    lng: 108.338,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Luang Prabang',
    country: 'Laos',
    description: 'Saffron-robed monks collect alms at dawn among gilded temples where the Mekong bends.',
    lat: 19.8845,
    lng: 102.1348,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Ahsan Manzil',
    country: 'Bangladesh',
    description: 'A pink palace on the Buriganga River once housed the nawabs who ruled old Dhaka.',
    lat: 23.7086,
    lng: 90.4058,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Badshahi Mosque',
    country: 'Pakistan',
    description: 'Mughal red sandstone and marble domes make one of the world’s largest mosques, in Lahore.',
    lat: 31.588,
    lng: 74.31,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Paro Taktsang',
    country: 'Bhutan',
    description: 'The Tiger’s Nest monastery clings to a sheer cliff face 3,000 feet above the Paro valley.',
    lat: 27.4919,
    lng: 89.3636,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Issyk-Kul Lake',
    country: 'Kyrgyzstan',
    description: 'A vast alpine lake that never freezes, ringed by snow peaks on the old Silk Road.',
    lat: 42.45,
    lng: 77.2,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Registan',
    country: 'Uzbekistan',
    description: 'Three tiled Islamic schools face a public square that anchored Silk Road Samarkand.',
    lat: 39.6542,
    lng: 66.975,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Tatev Monastery',
    country: 'Armenia',
    description: 'A ninth-century monastery perches above a gorge, reached by one of the world’s longest cable cars.',
    lat: 39.3789,
    lng: 46.25,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Gergeti Trinity Church',
    country: 'Georgia',
    description: 'A lone stone church stands beneath Mount Kazbek at 7,000 feet in the Caucasus.',
    lat: 42.6625,
    lng: 44.6183,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Flame Towers',
    country: 'Azerbaijan',
    description: 'Three glass skyscrapers shaped like flames light up Baku’s skyline above the Caspian.',
    lat: 40.3592,
    lng: 49.8419,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Persepolis',
    country: 'Iran',
    description: 'Carved stone stairways and column stumps are all that remain of a Persian imperial capital.',
    lat: 29.9356,
    lng: 52.8916,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Sultan Qaboos Grand Mosque',
    country: 'Oman',
    description: 'One of the world’s largest hand-loomed carpets fills a marble mosque in Muscat.',
    lat: 23.5225,
    lng: 58.4914,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Baalbek',
    country: 'Lebanon',
    description: 'Some of the largest stone blocks ever quarried support Roman temple columns in the Bekaa Valley.',
    lat: 34.0064,
    lng: 36.2039,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Taipei 101',
    country: 'Taiwan',
    description: 'A bamboo-inspired skyscraper with a giant tuned-mass damper once stood as the world’s tallest.',
    lat: 25.034,
    lng: 121.5645,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Victoria Peak',
    country: 'Hong Kong',
    description: 'A tram climbs to the highest point on Hong Kong Island for a skyline view over the harbor.',
    lat: 22.2759,
    lng: 114.1455,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Maldives Atolls',
    country: 'Maldives',
    description: 'Overwater bungalows ring coral atolls barely above sea level in the Indian Ocean.',
    lat: 4.1755,
    lng: 73.5093,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Sultan Omar Ali Saifuddien Mosque',
    country: 'Brunei',
    description: 'A golden dome floats above its own reflecting lagoon in the heart of Bandar Seri Begawan.',
    lat: 4.8903,
    lng: 114.9423,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Abu Simbel',
    country: 'Egypt',
    description: 'Four colossal statues of Ramesses II guard temples relocated stone by stone above the Nile.',
    lat: 22.3372,
    lng: 31.6258,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Karnak Temple',
    country: 'Egypt',
    description: 'A forest of towering columns forms the largest religious complex ever built, at Luxor.',
    lat: 25.7188,
    lng: 32.6573,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Chefchaouen',
    country: 'Morocco',
    description: 'Every wall and stairway is washed in shades of blue in this Rif Mountains hill town.',
    lat: 35.1688,
    lng: -5.2636,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Erg Chebbi Dunes',
    country: 'Morocco',
    description: 'Camel caravans cross towering orange dunes at the edge of the Sahara near Merzouga.',
    lat: 31.15,
    lng: -3.98,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Sidi Bou Said',
    country: 'Tunisia',
    description: 'Whitewashed, blue-shuttered houses tumble down a clifftop above the Gulf of Tunis.',
    lat: 36.8703,
    lng: 10.3417,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Casbah of Algiers',
    country: 'Algeria',
    description: 'A dense Ottoman-era citadel of narrow stairways spills down to the Algiers waterfront.',
    lat: 36.785,
    lng: 3.0608,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Meroe Pyramids',
    country: 'Sudan',
    description: 'Nubian pyramids sharper and more numerous than Egypt’s rise from the desert near the Nile.',
    lat: 16.9377,
    lng: 33.7519,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Volcanoes National Park',
    country: 'Rwanda',
    description: 'Mountain gorillas graze on bamboo slopes in the Virunga range where Dian Fossey once worked.',
    lat: -1.4795,
    lng: 29.5,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Bwindi Impenetrable Forest',
    country: 'Uganda',
    description: 'An ancient rainforest tangled with vines shelters half the world’s mountain gorillas.',
    lat: -1.03,
    lng: 29.6667,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Great Zimbabwe',
    country: 'Zimbabwe',
    description: 'Dry-stone walls up to eleven meters tall are the ruins of a medieval African capital.',
    lat: -20.268,
    lng: 30.9337,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Bazaruto Archipelago',
    country: 'Mozambique',
    description: 'Dune-backed islands and dugong-grazed seagrass meadows string along the Mozambique coast.',
    lat: -21.65,
    lng: 35.4667,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Avenue of the Baobabs',
    country: 'Madagascar',
    description: 'Ancient baobab trees line a dirt road like a cathedral nave at sunset near Morondava.',
    lat: -20.25,
    lng: 44.4167,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Gorée Island',
    country: 'Senegal',
    description: 'A small island off Dakar holds centuries of history behind its Door of No Return.',
    lat: 14.6672,
    lng: -17.3981,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Basilica of Our Lady of Peace',
    country: 'Ivory Coast',
    description: 'A domed basilica larger than St. Peter’s rises improbably from Yamoussoukro.',
    lat: 6.6989,
    lng: -5.2894,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Great Mosque of Djenné',
    country: 'Mali',
    description: 'The world’s largest mudbrick building is replastered each year by the whole town.',
    lat: 13.9058,
    lng: -4.555,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Anse Source d’Argent',
    country: 'Seychelles',
    description: 'Pink granite boulders frame one of the most photographed beaches on Earth.',
    lat: -4.3742,
    lng: 55.8319,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Le Morne Brabant',
    country: 'Mauritius',
    description: 'A basalt peak once sheltered escaped slaves and now overlooks a turquoise lagoon.',
    lat: -20.4522,
    lng: 57.3122,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Fogo Volcano',
    country: 'Cape Verde',
    description: 'Vineyards grow in the caldera of a still-active volcano rising from the mid-Atlantic.',
    lat: 14.95,
    lng: -24.35,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Virunga National Park',
    country: 'Democratic Republic of the Congo',
    description: 'Africa’s oldest national park holds a lava lake and some of the last mountain gorillas.',
    lat: -1.5197,
    lng: 29.25,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Lake Assal',
    country: 'Djibouti',
    description: 'A salt lake in a volcanic crater sits lower than any other point in Africa.',
    lat: 11.658,
    lng: 42.4142,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Lake Malawi',
    country: 'Malawi',
    description: 'Clear freshwater holds more fish species than any lake on Earth, ringed by golden beaches.',
    lat: -12,
    lng: 34.75,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Mlilwane Wildlife Sanctuary',
    country: 'Eswatini',
    description: 'Zebras and antelope roam freely through Eswatini’s oldest protected reserve.',
    lat: -26.4667,
    lng: 31.2,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Lake Louise',
    country: 'Canada',
    description: 'A glacier-fed lake of impossible turquoise sits beneath the peaks of Banff National Park.',
    lat: 51.4254,
    lng: -116.1773,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Old Québec',
    country: 'Canada',
    description: 'Cobbled ramparts and a chateau hotel make the only walled city north of Mexico.',
    lat: 46.8127,
    lng: -71.2044,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Teotihuacan',
    country: 'Mexico',
    description: 'The Pyramid of the Sun rises over an avenue laid out by a civilization that predates the Aztecs.',
    lat: 19.6925,
    lng: -98.8438,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Tulum Ruins',
    country: 'Mexico',
    description: 'Maya ruins perch on a limestone cliff above the turquoise Caribbean of the Yucatán.',
    lat: 20.2145,
    lng: -87.4295,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Great Blue Hole',
    country: 'Belize',
    description: 'A perfect blue circle drops 400 feet into a submerged limestone cave off the barrier reef.',
    lat: 17.316,
    lng: -87.535,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Arenal Volcano',
    country: 'Costa Rica',
    description: 'A near-symmetrical volcanic cone rises over hot springs and cloud forest in the north.',
    lat: 10.463,
    lng: -84.703,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Panama Canal',
    country: 'Panama',
    description: 'Massive locks lift ships between two oceans at the Miraflores gateway of the canal.',
    lat: 8.9943,
    lng: -79.599,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Copan Ruins',
    country: 'Honduras',
    description: 'Elaborately carved stelae mark a Maya city famed for its hieroglyphic staircase.',
    lat: 14.8372,
    lng: -89.1428,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Ometepe Island',
    country: 'Nicaragua',
    description: 'Two volcanoes joined by an isthmus rise from the middle of Lake Nicaragua.',
    lat: 11.5,
    lng: -85.5833,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Ataco',
    country: 'El Salvador',
    description: 'Mural-covered streets wind through a coffee-country town on the Ruta de las Flores.',
    lat: 13.8667,
    lng: -89.8167,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Sugarloaf Mountain',
    country: 'Brazil',
    description: 'A cable car climbs a granite peak jutting straight from Rio’s Guanabara Bay.',
    lat: -22.9492,
    lng: -43.1545,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Amazon Rainforest',
    country: 'Brazil',
    description: 'The world’s largest rainforest meets the Rio Negro at the river port of Manaus.',
    lat: -3.119,
    lng: -60.0217,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Perito Moreno Glacier',
    country: 'Argentina',
    description: 'A wall of blue ice three miles wide calves thunderously into a Patagonian lake.',
    lat: -50.4967,
    lng: -73.1367,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Recoleta Cemetery',
    country: 'Argentina',
    description: 'Marble mausoleums line a city of the dead in the heart of elegant Buenos Aires.',
    lat: -34.5875,
    lng: -58.3931,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Atacama Desert',
    country: 'Chile',
    description: 'The driest place on Earth stretches in salt flats and geysers around San Pedro de Atacama.',
    lat: -22.911,
    lng: -68.1997,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Rainbow Mountain',
    country: 'Peru',
    description: 'Mineral bands stripe a 17,000-foot Andean peak in bands of red, gold, and turquoise.',
    lat: -13.872,
    lng: -71.3072,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Lake Titicaca',
    country: 'Peru',
    description: 'Reed islands built by hand float on the highest navigable lake in the world.',
    lat: -15.8402,
    lng: -70.0219,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Colonia del Sacramento',
    country: 'Uruguay',
    description: 'Portuguese cobblestones and a lighthouse mark one of South America’s oldest towns.',
    lat: -34.4718,
    lng: -57.8442,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Jesuit Missions of Trinidad',
    country: 'Paraguay',
    description: 'Red sandstone ruins of a 18th-century Jesuit reduction stand amid Paraguayan grassland.',
    lat: -27.0264,
    lng: -55.6067,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Punta Cana',
    country: 'Dominican Republic',
    description: 'Coconut palms line miles of white sand along the Caribbean’s eastern tip.',
    lat: 18.5601,
    lng: -68.3725,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Old San Juan',
    country: 'Puerto Rico',
    description: 'Pastel colonial buildings and centuries-old fortresses guard the oldest city under the U.S. flag.',
    lat: 18.4663,
    lng: -66.1057,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Exuma Cays',
    country: 'Bahamas',
    description: 'Swimming pigs and sandbars dot a scattering of cays in impossibly clear water.',
    lat: 23.5167,
    lng: -75.8333,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Pitch Lake',
    country: 'Trinidad and Tobago',
    description: 'The world’s largest natural asphalt lake still bubbles slowly in southwest Trinidad.',
    lat: 10.24,
    lng: -61.635,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Harrison’s Cave',
    country: 'Barbados',
    description: 'A tram winds through a live limestone cavern of streams and crystal formations.',
    lat: 13.1939,
    lng: -59.5661,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Kaieteur Falls',
    country: 'Guyana',
    description: 'A single drop nearly five times the height of Niagara plunges through Guyana’s rainforest.',
    lat: 5.1706,
    lng: -59.4939,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Paramaribo Historic Inner City',
    country: 'Suriname',
    description: 'Dutch colonial wooden architecture lines the banks of the Suriname River.',
    lat: 5.852,
    lng: -55.2038,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Times Square',
    country: 'United States',
    description: 'Billboards blaze around the clock where Broadway crosses Seventh Avenue in Manhattan.',
    lat: 40.758,
    lng: -73.9855,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Central Park',
    country: 'United States',
    description: 'Eight hundred forty acres of engineered wilderness sit at the center of New York City.',
    lat: 40.7829,
    lng: -73.9654,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Washington Monument',
    country: 'United States',
    description: 'A 555-foot marble obelisk on the National Mall honors the first U.S. president.',
    lat: 38.8895,
    lng: -77.0353,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Lincoln Memorial',
    country: 'United States',
    description: 'A seated marble Lincoln gazes down the Reflecting Pool toward the Washington Monument.',
    lat: 38.8893,
    lng: -77.0502,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Las Vegas Strip',
    country: 'United States',
    description: 'Neon casino towers and fountain shows light up four miles of Nevada desert highway.',
    lat: 36.1147,
    lng: -115.1728,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Hollywood Sign',
    country: 'United States',
    description: 'Fifty-foot white letters have watched over Los Angeles from Mount Lee since 1923.',
    lat: 34.1341,
    lng: -118.3215,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Zion National Park',
    country: 'United States',
    description: 'Sandstone cliffs in red and cream tower thousands of feet above the Virgin River.',
    lat: 37.2982,
    lng: -113.0263,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Bryce Canyon',
    country: 'United States',
    description: 'Thousands of orange hoodoo spires fill a natural amphitheater carved into the Utah plateau.',
    lat: 37.593,
    lng: -112.1871,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Sequoia National Park',
    country: 'United States',
    description: 'General Sherman and other giant sequoias tower as the largest living trees on Earth.',
    lat: 36.4864,
    lng: -118.5658,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Antelope Canyon',
    country: 'United States',
    description: 'Sunbeams slice through the swirling sandstone walls of a slot canyon on Navajo land.',
    lat: 36.8619,
    lng: -111.3743,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Mount Rainier',
    country: 'United States',
    description: 'A glacier-capped volcano dominates the skyline south of Seattle at over 14,000 feet.',
    lat: 46.8523,
    lng: -121.7603,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Everglades National Park',
    country: 'United States',
    description: 'A slow-moving river of grass shelters alligators, manatees, and mangrove wilderness.',
    lat: 25.2866,
    lng: -80.8987,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Multnomah Falls',
    country: 'United States',
    description: 'Water drops 620 feet in two tiers through the Columbia River Gorge.',
    lat: 45.5762,
    lng: -122.1158,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Carlsbad Caverns',
    country: 'United States',
    description: 'A vast underground chamber and nightly bat flight lie beneath the Chihuahuan Desert.',
    lat: 32.1479,
    lng: -104.5567,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Badlands National Park',
    country: 'United States',
    description: 'Striped sedimentary spires and canyons stretch across the South Dakota prairie.',
    lat: 43.8554,
    lng: -102.3397,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Redwood National Park',
    country: 'United States',
    description: 'Coast redwoods, the tallest trees on Earth, tower along California’s northern coast.',
    lat: 41.2132,
    lng: -124.0046,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'USS Arizona Memorial',
    country: 'United States',
    description: 'A white memorial spans the sunken battleship’s hull in Pearl Harbor, Oahu.',
    lat: 21.3649,
    lng: -157.95,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Kennedy Space Center',
    country: 'United States',
    description: 'Launch pads that sent astronauts to the Moon still send rockets skyward on Florida’s coast.',
    lat: 28.5729,
    lng: -80.649,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Alcatraz Island',
    country: 'United States',
    description: 'A former federal prison sits isolated in the cold currents of San Francisco Bay.',
    lat: 37.8267,
    lng: -122.423,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Brooklyn Bridge',
    country: 'United States',
    description: 'Gothic stone towers and steel cables have carried traffic over the East River since 1883.',
    lat: 40.7061,
    lng: -73.9969,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Uluru',
    country: 'Australia',
    description: 'A vast sandstone monolith glows red at sunset in the heart of the Australian Outback.',
    lat: -25.3444,
    lng: 131.0369,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Great Barrier Reef',
    country: 'Australia',
    description: 'The world’s largest coral reef system stretches for 1,400 miles off the Queensland coast.',
    lat: -20.27,
    lng: 148.9,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Twelve Apostles',
    country: 'Australia',
    description: 'Limestone sea stacks rise from the Southern Ocean along Victoria’s Great Ocean Road.',
    lat: -38.6662,
    lng: 143.1044,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Bondi Beach',
    country: 'Australia',
    description: 'Surfers and sunbathers fill Sydney’s most famous crescent of golden sand.',
    lat: -33.8908,
    lng: 151.2743,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Hobbiton',
    country: 'New Zealand',
    description: 'Round doors dot green hillside hobbit-holes built for the screen in the Waikato countryside.',
    lat: -37.8722,
    lng: 175.682,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Tongariro National Park',
    country: 'New Zealand',
    description: 'Active volcanoes and emerald crater lakes line one of the world’s great day hikes.',
    lat: -39.142,
    lng: 175.6428,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Mamanuca Islands',
    country: 'Fiji',
    description: 'A necklace of small coral islands and reef breaks scatters west of Fiji’s main island.',
    lat: -17.67,
    lng: 177.1,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Port Vila',
    country: 'Vanuatu',
    description: 'Volcanic islands and clear lagoons surround Vanuatu’s laid-back harbor capital.',
    lat: -17.7333,
    lng: 168.3273,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Kokoda Track',
    country: 'Papua New Guinea',
    description: 'A rugged jungle trail through the Owen Stanley Range carries deep wartime history.',
    lat: -8.7,
    lng: 147.7333,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'To Sua Ocean Trench',
    country: 'Samoa',
    description: 'A ladder descends into a giant sunken garden pool connected to the sea by lava tubes.',
    lat: -13.9333,
    lng: -171.7167,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Nuku’alofa',
    country: 'Tonga',
    description: 'Royal tombs and coral coastline meet in the capital of the last Polynesian kingdom.',
    lat: -21.1393,
    lng: -175.2049,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Rock Islands',
    country: 'Palau',
    description: 'Mushroom-shaped limestone islets dot a lagoon famous for its jellyfish lake.',
    lat: 7.25,
    lng: 134.3833,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Bikini Atoll',
    country: 'Marshall Islands',
    description: 'A ring of coral islets and sunken warships bears witness to the mid-century nuclear tests.',
    lat: 11.5833,
    lng: 165.3833,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Nan Madol',
    country: 'Micronesia',
    description: 'Basalt-log ruins rise from a lagoon on Pohnpei, a Pacific city built on artificial islets.',
    lat: 6.8419,
    lng: 158.3339,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Honiara',
    country: 'Solomon Islands',
    description: 'Rainforest ridges and WWII relics surround the Solomon Islands’ harborside capital.',
    lat: -9.4333,
    lng: 159.95,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Aitutaki Lagoon',
    country: 'Cook Islands',
    description: 'A turquoise lagoon rings a near-atoll often ranked among the world’s most beautiful.',
    lat: -18.83,
    lng: -159.77,
    artKey: null,
    category: 'landmark',
  },
  {
    name: 'Nouméa',
    country: 'New Caledonia',
    description: 'A French Pacific capital sits beside the world’s largest lagoon, ringed by barrier reef.',
    lat: -22.2758,
    lng: 166.4581,
    artKey: null,
    category: 'city',
  },
  {
    name: 'Tarawa Atoll',
    country: 'Kiribati',
    description: 'A slender ring of coral islets holds the front line of a nation facing rising seas.',
    lat: 1.4518,
    lng: 173,
    artKey: null,
    category: 'landmark',
  },

];
